racial:
 elves:
  effects:
   - NIGHT_VISION
   - JUMP
 humans:
  effects:
   - SPEED
 orcs:
  effects:
   - STRENGTH
 gnomes:
  effects:
   - LUCK
 gods:
  effects:
   - INSTANT_HEAL
   - LUCK
   - WATER_BREATHING
 demons:
  effects:
   - STRENGTH
   - REGEN
   - INVISIBILITY
players:
 elves:
  - honses
 orcs:
 gnomes:
 humans:
 gods:
 demons:

