race:
 elves:
  effects:
   - NIGHT_VISION
   - JUMP
 humans:
  effects:
   - SPEED
 orcs:
  effects:
   - INCREASE_DAMAGE
 gnomes:
  effects:
   - LUCK
 gods:
  effects:
   - HEALTH_BOOST
   - LUCK
   - WATER_BREATHING
 demons:
  effects:
   - INCREASE_DAMAGE
   - REGENERATION
   - INVISIBILITY
players:
 elves: []
 orcs: []
 gnomes: []
 humans: []
 gods: []
 demons: []
info:
 - elves
 - orcs
 - gnomes
 - humans
 - gods
 - demons
effectInfo:
 - HERO_OF_THE_VILLAGE
 - BAD_OMEN
 - DOLPHINS_GRACE
 - CONDUIT_POWER
 - SLOW_FALLING
 - UNLUCK
 - LUCK
 - LEVITATION
 - GLOWING
 - SATURATION
 - ABSORPTION
 - HEALTH_BOOST
 - WITHER
 - POISON
 - WEAKNESS
 - HUNGER
 - NIGHT_VISION
 - BLINDNESS
 - INVISIBILITY
 - WATER_BREATHING
 - FIRE_RESISTANCE
 - DAMAGE_RESISTANCE
 - REGENERATION
 - CONFUSION
 - JUMP
 - HARM
 - HEAL
 - INCREASE_DAMAGE
 - SLOW_DIGGING
 - FAST_DIGGING
 - SLOW
 - SPEED
