name: RacialDiversity
version: '${project.version}'
main: racialdiversity.racialdiversity.main
api-version: 1.16
author: 4e1owek
commands:
  racial:
    name: /racial
    use: /racial <humans|elves|orcs|gnomes>